"use client";

import { motion } from "framer-motion";

export default function TermsPage() {
  return (
    <div className="pt-24">
      {/* Hero Section */}
      <section className="section-padding">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-3xl mx-auto text-center"
          >
            <span className="inline-block px-4 py-2 rounded-full bg-[var(--rose-light)] text-[var(--rose-dark)] text-sm font-medium mb-6">
              Legal
            </span>
            <h1 className="text-5xl md:text-6xl font-medium mb-6">
              Terms of Service
            </h1>
            <p className="text-xl text-[var(--soft-gray)] leading-relaxed">
              Please read these terms carefully before using Tea - AI Chatbot.
            </p>
            <p className="text-sm text-[var(--soft-gray)] mt-4">
              Last updated: December 2024
            </p>
          </motion.div>
        </div>
      </section>

      {/* Content */}
      <section className="section-padding bg-white">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="legal-content"
          >
            <h2>1. Agreement to Terms</h2>
            <p>
              These Terms of Service (&quot;Terms&quot;) constitute a legally binding agreement
              between you (&quot;User,&quot; &quot;you,&quot; or &quot;your&quot;) and Tribe Industries Inc
              (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) regarding your access to and use
              of the Tea - AI Chatbot mobile application (&quot;App&quot;) and any related
              services.
            </p>
            <p>
              BY ACCESSING OR USING THE APP, YOU AGREE TO BE BOUND BY THESE TERMS. IF
              YOU DO NOT AGREE TO THESE TERMS, DO NOT USE THE APP.
            </p>

            <h2>2. Eligibility and Account Requirements</h2>

            <h3>2.1 Age Requirement</h3>
            <p>
              You must be at least 18 years of age to use this App. If you are between
              13 and 18 years of age, you may only use the App with the consent and
              supervision of a parent or legal guardian who agrees to be bound by these
              Terms. The App is not intended for children under 13.
            </p>

            <h3>2.2 Account Responsibility</h3>
            <p>
              You are responsible for maintaining the confidentiality of your account
              credentials and for all activities that occur under your account. You
              agree to notify us immediately of any unauthorized use of your account.
            </p>

            <h2>3. AI-Generated Content Disclaimer</h2>

            <div style={{ background: 'var(--rose-light)', padding: '24px', borderRadius: '16px', margin: '24px 0' }}>
              <h3 style={{ marginTop: 0, color: 'var(--charcoal)' }}>IMPORTANT DISCLAIMER</h3>
              <p style={{ color: 'var(--charcoal)', marginBottom: '16px' }}>
                <strong>Tea is an AI-powered chatbot designed for informational and entertainment
                purposes only.</strong> The AI-generated responses, advice, suggestions, and content
                provided through the App:
              </p>
              <ul style={{ color: 'var(--charcoal)' }}>
                <li>ARE NOT professional advice of any kind</li>
                <li>ARE NOT a substitute for professional medical, mental health, legal, financial, or other professional advice</li>
                <li>MAY contain errors, inaccuracies, or outdated information</li>
                <li>SHOULD NOT be relied upon for important decisions</li>
              </ul>
            </div>

            <h3>3.1 No Professional Advice</h3>
            <p>
              The App does not provide medical, psychological, legal, financial, or any
              other professional advice. AI responses are generated by machine learning
              models and should never be considered a substitute for consultation with
              qualified professionals.
            </p>
            <p>
              <strong>If you are experiencing a medical emergency, mental health crisis,
              or any situation requiring immediate professional assistance, please
              contact emergency services or appropriate professionals immediately.</strong>
            </p>

            <h3>3.2 AI Limitations</h3>
            <p>
              You acknowledge and understand that:
            </p>
            <ul>
              <li>AI responses may be inaccurate, incomplete, or inappropriate</li>
              <li>The AI may produce content that is factually incorrect</li>
              <li>The AI does not have access to real-time information</li>
              <li>The AI cannot verify the accuracy of information provided to it</li>
              <li>AI-generated images may contain imperfections or unexpected content</li>
            </ul>

            <h3>3.3 User Responsibility</h3>
            <p>
              <strong>YOU ARE SOLELY RESPONSIBLE FOR ANY ACTIONS YOU TAKE BASED ON
              AI-GENERATED CONTENT.</strong> You agree to:
            </p>
            <ul>
              <li>Independently verify any information before relying on it</li>
              <li>Consult appropriate professionals for important decisions</li>
              <li>Use your own judgment when evaluating AI responses</li>
              <li>Not hold the Company liable for actions taken based on AI content</li>
            </ul>

            <h2>4. Subscription and Payment Terms</h2>

            <h3>4.1 Subscription Plans</h3>
            <p>
              The App may offer free and premium subscription tiers. Premium features
              require a paid subscription. Subscription details, including pricing and
              features, are displayed in the App.
            </p>

            <h3>4.2 Billing</h3>
            <p>
              All payments are processed through Apple&apos;s App Store. By subscribing, you
              agree to Apple&apos;s payment terms. Subscriptions automatically renew unless
              canceled at least 24 hours before the end of the current billing period.
            </p>

            <h3>4.3 Refund Policy</h3>
            <p>
              Refund requests are handled by Apple in accordance with their refund
              policies. We do not directly process refunds. To request a refund,
              please contact Apple Support or use the &quot;Report a Problem&quot; feature in
              your App Store purchase history.
            </p>
            <p>
              We may, at our sole discretion, offer refunds or credits in certain
              circumstances, but we are under no obligation to do so.
            </p>

            <h3>4.4 Price Changes</h3>
            <p>
              We reserve the right to change subscription prices. Any price changes
              will be communicated in advance and will apply to the next billing cycle.
            </p>

            <h2>5. Acceptable Use Policy</h2>

            <h3>5.1 Prohibited Uses</h3>
            <p>You agree NOT to use the App to:</p>
            <ul>
              <li>Generate illegal, harmful, or abusive content</li>
              <li>Harass, threaten, or harm others</li>
              <li>Create content that exploits minors</li>
              <li>Generate content that infringes intellectual property rights</li>
              <li>Attempt to circumvent safety measures or content filters</li>
              <li>Use the App for commercial purposes without authorization</li>
              <li>Reverse engineer or attempt to extract the AI model</li>
              <li>Share account access with others</li>
              <li>Automate access to the App without permission</li>
              <li>Violate any applicable laws or regulations</li>
            </ul>

            <h3>5.2 Content Guidelines</h3>
            <p>
              We reserve the right to remove any content and suspend or terminate
              accounts that violate these Terms or our content guidelines.
            </p>

            <h2>6. Intellectual Property</h2>

            <h3>6.1 Our Property</h3>
            <p>
              The App, including its design, features, content, and underlying
              technology, is owned by Tribe Industries Inc and protected by
              intellectual property laws. You may not copy, modify, distribute,
              or create derivative works without our written permission.
            </p>

            <h3>6.2 Your Content</h3>
            <p>
              You retain ownership of content you submit to the App. By using the
              App, you grant us a license to use your content to provide and improve
              our services.
            </p>

            <h3>6.3 AI-Generated Content</h3>
            <p>
              AI-generated text and images created through the App may be used by you
              for personal, non-commercial purposes, subject to these Terms and
              applicable laws.
            </p>

            <h2>7. Limitation of Liability</h2>

            <div style={{ background: 'var(--rose-light)', padding: '24px', borderRadius: '16px', margin: '24px 0' }}>
              <p style={{ color: 'var(--charcoal)', fontWeight: 600, marginBottom: '16px' }}>
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
              </p>
              <p style={{ color: 'var(--charcoal)', marginBottom: '16px' }}>
                THE APP IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF
                ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES
                OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
              </p>
              <p style={{ color: 'var(--charcoal)', marginBottom: '16px' }}>
                IN NO EVENT SHALL TRIBE INDUSTRIES INC, ITS OFFICERS, DIRECTORS,
                EMPLOYEES, AGENTS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
                SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul style={{ color: 'var(--charcoal)' }}>
                <li>Loss of profits, data, or goodwill</li>
                <li>Personal injury or emotional distress</li>
                <li>Damages arising from reliance on AI-generated content</li>
                <li>Damages from actions taken based on AI advice or suggestions</li>
                <li>Service interruptions or data loss</li>
              </ul>
            </div>

            <h3>7.1 Maximum Liability</h3>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY TO YOU FOR
              ALL CLAIMS ARISING FROM OR RELATED TO THE APP SHALL NOT EXCEED THE AMOUNT
              YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR $100 USD,
              WHICHEVER IS GREATER.
            </p>

            <h3>7.2 Basis of the Bargain</h3>
            <p>
              You acknowledge that these limitations of liability reflect a reasonable
              allocation of risk and are a fundamental element of the agreement between
              you and the Company.
            </p>

            <h2>8. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless Tribe Industries Inc
              and its officers, directors, employees, agents, and affiliates from and
              against any and all claims, damages, losses, costs, and expenses
              (including reasonable attorneys&apos; fees) arising from or related to:
            </p>
            <ul>
              <li>Your use of the App</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any third-party rights</li>
              <li>Any content you submit through the App</li>
              <li>Your actions or decisions based on AI-generated content</li>
            </ul>

            <h2>9. Dispute Resolution</h2>

            <h3>9.1 Governing Law</h3>
            <p>
              These Terms shall be governed by and construed in accordance with the
              laws of the State of Utah, United States, without regard to its conflict
              of law provisions.
            </p>

            <h3>9.2 Arbitration</h3>
            <p>
              Any dispute, controversy, or claim arising out of or relating to these
              Terms or the App shall be resolved by binding arbitration in accordance
              with the rules of the American Arbitration Association. The arbitration
              shall take place in Utah, and the language of arbitration shall be English.
            </p>

            <h3>9.3 Class Action Waiver</h3>
            <p>
              YOU AGREE THAT ANY CLAIMS WILL BE BROUGHT IN YOUR INDIVIDUAL CAPACITY
              AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE
              PROCEEDING.
            </p>

            <h2>10. Termination</h2>
            <p>
              We may terminate or suspend your access to the App immediately, without
              prior notice or liability, for any reason, including if you breach these
              Terms. Upon termination, your right to use the App will cease immediately.
            </p>

            <h2>11. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify
              you of material changes by posting the updated Terms in the App or by
              other means. Your continued use of the App after changes constitutes
              acceptance of the modified Terms.
            </p>

            <h2>12. Severability</h2>
            <p>
              If any provision of these Terms is found to be unenforceable, the
              remaining provisions will continue in full force and effect.
            </p>

            <h2>13. Entire Agreement</h2>
            <p>
              These Terms, together with our Privacy Policy, constitute the entire
              agreement between you and Tribe Industries Inc regarding the App and
              supersede any prior agreements.
            </p>

            <h2>14. Contact Information</h2>
            <p>
              For questions about these Terms, please contact us:
            </p>
            <ul>
              <li>Email: legal@[PLACEHOLDER].com</li>
              <li>Company: Tribe Industries Inc</li>
              <li>Location: Utah, USA</li>
            </ul>

            <div style={{ background: 'var(--cream)', padding: '24px', borderRadius: '16px', margin: '32px 0', textAlign: 'center' }}>
              <p style={{ color: 'var(--charcoal)', fontWeight: 500, marginBottom: '8px' }}>
                By using Tea - AI Chatbot, you acknowledge that you have read,
                understood, and agree to be bound by these Terms of Service.
              </p>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
